from yacs.config import CfgNode as CN
import getpass
username = getpass.getuser()

_C = CN()
cfg = _C

_C.LOADER = CN()

_C.LOADER.SAMPLER = CN()
_C.LOADER.SAMPLER.TYPE = "sequence"
_C.LOADER.SAMPLER.GAMMA = 0.1
_C.LOADER.NUM_WORKS = 4

_C.MODEL = CN()
_C.MODEL.ARCH = 'Standard'
_C.MODEL.FEATURE_DIM = 128
_C.MODEL.EPISODIC = False
_C.MODEL.PROJECTION = CN()
_C.MODEL.PROJECTION.HEAD = "linear"
_C.MODEL.PROJECTION.EMB_DIM = 2048
_C.MODEL.PROJECTION.FEA_DIM = 128
_C.MODEL.ADAPTATION = 'source'
_C.MODEL.CKPT_PATH = None

_C.CORRUPTION = CN()
_C.CORRUPTION.DATASET = 'imagenet'
_C.CORRUPTION.SOURCE = ''
_C.CORRUPTION.TYPE = ['motion_blur','snow', 'fog', 'shot_noise',
                      'defocus_blur', 'contrast', 'zoom_blur', 'brightness',
                      'frost', 'elastic_transform', 'glass_blur', 'gaussian_noise', 'pixelate',
                      'jpeg_compression', 'impulse_noise']


_C.CORRUPTION.SEVERITY = [5]
_C.CORRUPTION.NUM_EX = 5000
_C.CORRUPTION.NUM_CLASS = -1
_C.CORRUPTION.ORDER_NUM = 0

_C.INPUT = CN()
_C.INPUT.SIZE = (32, 32)
_C.INPUT.INTERPOLATION = "bilinear"
_C.INPUT.INTERPOLATION = "bilinear"
_C.INPUT.PIXEL_MEAN = [0.485, 0.456, 0.406]
_C.INPUT.PIXEL_STD = [0.229, 0.224, 0.225]
_C.INPUT.TRANSFORMS = ("normalize", )
_C.INPUT.BLIND_SPOT_MODE = "SOURCE_ERROR"

_C.OPTIM = CN()
_C.OPTIM.STEPS = 1
_C.OPTIM.LR = 0.00025
_C.OPTIM.METHOD = 'SGD'
_C.OPTIM.BETA = 0.9
_C.OPTIM.MOMENTUM = 0.9
_C.OPTIM.WD = 0.0
_C.OPTIM.EPS = 1e-5
_C.OPTIM.DAMPENING = 0.0
_C.OPTIM.NESTEROV = True

_C.TEST = CN()
_C.TEST.BATCH_SIZE = 64
_C.TEST.COLLECT = False
_C.TEST.ROUNDS = 40


_C.SEED = -1
_C.OUTPUT_DIR = "./output"
_C.DATA_DIR = f"/gemini/data-1/datasets"
_C.NOTE = 'none'
_C.CKPT_DIR = "./models"
_C.CKPT_PATH = "./models"
_C.LOG_DIR = "./log"
_C.DEBUG = False
_C.ENABLE_PROGRESS_BAR = False
_C.SETTING = ''

_C.ADAPTER = CN()
_C.ADAPTER.NAME = "Tent"

_C.ADAPTER.CoTTA = CN()
_C.ADAPTER.CoTTA.RST = 0.01
_C.ADAPTER.CoTTA.AP = 0.92
_C.ADAPTER.CoTTA.MT = 0.999

_C.ADAPTER.RoTTA = CN()
_C.ADAPTER.RoTTA.MEMORY_SIZE = 64
_C.ADAPTER.RoTTA.UPDATE_FREQUENCY = 64
_C.ADAPTER.RoTTA.NU = 0.001
_C.ADAPTER.RoTTA.ALPHA = 0.05
_C.ADAPTER.RoTTA.LAMBDA_T = 1.0
_C.ADAPTER.RoTTA.LAMBDA_U = 1.0

_C.ADAPTER.DeYO = CN()
_C.ADAPTER.DeYO.REWEIGHT_ENT = True
_C.ADAPTER.DeYO.REWEIGHT_PLPD = True
_C.ADAPTER.DeYO.PLPD = 0.2
_C.ADAPTER.DeYO.MARGIN = 0.5       
_C.ADAPTER.DeYO.AUG_TYPE = "patch" 
_C.ADAPTER.DeYO.OCCLUSION_SIZE = 112    
_C.ADAPTER.DeYO.ROW_START = 56        
_C.ADAPTER.DeYO.COLUMN_START = 56          
_C.ADAPTER.DeYO.PATCH_LEN = 4          
_C.ADAPTER.DeYO.D_MARGIN = 0.05
_C.ADAPTER.DeYO.MARGIN_E0 = 0.4 

_C.ADAPTER.ETA = CN()
_C.ADAPTER.ETA.FISHER_ALPHA = 0.05
_C.ADAPTER.ETA.D_MARGIN = 0.05
_C.ADAPTER.ETA.NUM_SAMPLES = 2000
_C.ADAPTER.ETA.E_MARGIN = 0.4

_C.ADAPTER.MGP = CN()
_C.ADAPTER.MGP.DISTILL_FREQ = 100
_C.ADAPTER.MGP.BUFFER_SIZE = 32
_C.ADAPTER.MGP.MAX_RANK = 32
_C.ADAPTER.MGP.RESIDUAL_NORM_THRESHOLD = 0.75

_C.ADAPTER.SPA = CN()
_C.ADAPTER.SPA.NOISE_RATIO = 0.4
_C.ADAPTER.SPA.FREQ_MASK_RATIO = 0.2

_C.ADAPTER.COME = CN()

_C.ADAPTER.Tent = CN()

_C.ADAPTER.PTTA = CN()
_C.ADAPTER.PTTA.e_margin = 2.76 
_C.ADAPTER.PTTA.d_margin = 0.05
_C.ADAPTER.PTTA.loss2_weight = 3.0 
_C.ADAPTER.PTTA.queue_size = 1000
_C.ADAPTER.PTTA.neighbor = 1

_C.ADAPTER.ViDA = CN()
_C.ADAPTER.ViDA.ViDALR = 2e-07 
_C.ADAPTER.ViDA.MT = 0.999 
_C.ADAPTER.ViDA.MT_ViDA = 0.8
_C.ADAPTER.ViDA.RANK1 = 1 
_C.ADAPTER.ViDA.RANK2 = 128 
_C.ADAPTER.ViDA.UNC_THR = 0.2

_C.ADAPTER.TRIBE = CN()
_C.ADAPTER.TRIBE.ETA = 0.005
_C.ADAPTER.TRIBE.GAMMA = 0.0
_C.ADAPTER.TRIBE.LAMBDA = 0.5
_C.ADAPTER.TRIBE.H0 = 0.05

_C.ADAPTER.SAR = CN()

_C.ADAPTER.Source = CN()

_CFG_DEFAULT = _C.clone()
_CFG_DEFAULT.freeze()

